-- -----------------------------------------------------
-- utilisation du schema wineManager
-- -----------------------------------------------------
USE `wineManager` ;

-- -----------------------------------------------------
-- insertion des données dans la table 'grapeVarieties'
-- -----------------------------------------------------

INSERT INTO grapeVarieties (varietyName) VALUES ('Abondant blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Abouriou noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Aléatico noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Alicante Henri Bouschet noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Aligoté blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Alphonse Lavallée noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Altesse blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Alvarinho blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Araignan blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Aramon blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Aramon gris');
INSERT INTO grapeVarieties (varietyName) VALUES ('Aramon noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Aranel blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Arbane blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Arinarnoa noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Arriloba blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Arrouya noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Arrufiac blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Arvine blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Aubin blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Aubin vert blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Aubun noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Auxerrois blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Bachet noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Baco blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Barbaroux rosé');
INSERT INTO grapeVarieties (varietyName) VALUES ('Baroque blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Béclan noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Béquignol noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Biancu Gentile blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Blanc Dame blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Blanqueiron blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Bouchalès noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Bouillet noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Bouquettraube blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Bourboulenc blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Bouteillan blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Brachet noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Brun Argenté noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Brun Fourca noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Cabernet-Franc noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Cabernet-Sauvignon noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Caladoc noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Calitor noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Camaralet blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Carcajolo blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Carcajolo noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Cardinal rouge');
INSERT INTO grapeVarieties (varietyName) VALUES ('Carignan blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Carignan noir ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Carmenère noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Castets noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('César noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Chambourcin noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Chardonnay blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Chasan blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Chasselas blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Chasselas rosé');
INSERT INTO grapeVarieties (varietyName) VALUES ('Chatus noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Chenanson noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Chenin blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Cinsaut noir ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Clairette blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Clairette rosé');
INSERT INTO grapeVarieties (varietyName) VALUES ('Clarin blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Claverie blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Codivarta blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Colobel noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Colombard blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Corbeau noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Cot noir ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Couderc noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Counoise noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Courbu blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Courbu noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Couston noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Crouchen blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Danlas blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Duras noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Durif noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Egiodola noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Ekigaïna noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Elbling blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Etraire de la Dui noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Ferradou noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Fer-servadou noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Feunate noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Florental noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Folignan blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Folle Blanche blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Franc noir de Haute-Saône noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Fuella nera noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Furmint blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gamaret noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gamay de Bouze noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gamay de Chaudenay noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gamay Fréaux noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gamay noir ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Ganson noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Garonnet noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gascon noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Genovèse blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gewurztraminer rosé ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Goldriesling blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gouget noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Graisse blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gramon noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Grassen noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Grenache blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Grenache gris ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Grenache noir ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gringet blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Grolleau gris gris');
INSERT INTO grapeVarieties (varietyName) VALUES ('Grolleau noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gros Manseng blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Gros vert blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Jacquère blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Joubertin noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Jurançon blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Jurançon noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Knipperlé blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Landal noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Lauzet blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Len de l’El blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Léon Millot noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Liliorila blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Listan blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Lival noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Lledoner Pelut noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Macabeu blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mancin noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Manseng noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Maréchal Foch noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Marsanne blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Marselan noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mauzac blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mauzac rosé');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mayorquin blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mècle noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Melon blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mérille noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Merlot blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Merlot noir ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Meslier Saint-François blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Meunier noir ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Milgranet noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Molette blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mollard noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mondeuse blanche blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mondeuse noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Monerac noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Montils blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mornen noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Morrastel noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mourvaison noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mourvèdre noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Mouyssaguès noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Müller-Thurgau blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Muresconu noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Muscadelle blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Muscardin noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Muscat à petits grains blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Muscat à petits grains rouges noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Muscat à petits grains rosé');
INSERT INTO grapeVarieties (varietyName) VALUES ('Muscat cendré blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Muscat d’Alexandrie blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Muscat de Hambourg noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Muscat Ottonel blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Négret de Banhars noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Négrette noir ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Nielluccio noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Noir Fleurien noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Oberlin noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Ondenc blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Orbois blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Pagadebiti blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Panse muscade blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Parellada blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Pascal blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Perdea blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Persan noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Petit brun noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Petit Courbu blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Petit Manseng blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Petit Meslier blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Petit Verdot noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Picardan blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Pineau d\'Aunis noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Pinot blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Pinot gris');
INSERT INTO grapeVarieties (varietyName) VALUES ('Pinot noir ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Piquepoul blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Piquepoul gris');
INSERT INTO grapeVarieties (varietyName) VALUES ('Piquepoul noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Plant de Brunel noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Plant droit noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Plantet noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Portan noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Portugais bleu noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Poulsard noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Précoce Bousquet blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Précoce de Malingre blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Prunelard noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Raffiat de Moncade blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Ravat blanc blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Rayon d\'or blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Ribol noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Riesling blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Riminèse blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Rivairenc blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Rivairenc gris');
INSERT INTO grapeVarieties (varietyName) VALUES ('Rivairenc noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Romorantin blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Rosé du Var rosé');
INSERT INTO grapeVarieties (varietyName) VALUES ('Roublot blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Roussanne blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Roussette d\'Ayze blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Rubilande rosé');
INSERT INTO grapeVarieties (varietyName) VALUES ('Sacy blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Saint-Côme blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Saint-Macaire noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Saint-Pierre doré blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Sauvignon blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Sauvignon gris');
INSERT INTO grapeVarieties (varietyName) VALUES ('Savagnin blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Savagnin rosé');
INSERT INTO grapeVarieties (varietyName) VALUES ('Sciaccarello noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Ségalin noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Seinoir noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Select blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Semebat noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Sémillon blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Servanin noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Servant blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Seyval blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Sylvaner blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Syrah noir ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Tannat noir ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Tempranillo noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Téoulier noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Terret blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Terret gris');
INSERT INTO grapeVarieties (varietyName) VALUES ('Terret noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Tibouren noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Tourbat blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Tressot noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Trousseau gris');
INSERT INTO grapeVarieties (varietyName) VALUES ('Trousseau noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Ugni blanc ');
INSERT INTO grapeVarieties (varietyName) VALUES ('Valdiguié noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Valérien blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Varousset noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Velteliner rouge précoce rosé');
INSERT INTO grapeVarieties (varietyName) VALUES ('Verdelho blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Verdesse blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Vermentino blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Villard blanc');
INSERT INTO grapeVarieties (varietyName) VALUES ('Villard noir');
INSERT INTO grapeVarieties (varietyName) VALUES ('Viognier blanc ');
