-- -----------------------------------------------------
-- utilisation du schema wineManager
-- -----------------------------------------------------
USE `wineManager` ;

-- -----------------------------------------------------
-- insertion des données dans la table 'country'
-- -----------------------------------------------------
INSERT INTO `countries` (countryName) VALUES ('Ghana');
INSERT INTO `countries` (countryName) VALUES ('Trinidad et Tobago');
INSERT INTO `countries` (countryName) VALUES ('Congo, Republique Democratique');
INSERT INTO `countries` (countryName) VALUES ('Bhutan');
INSERT INTO `countries` (countryName) VALUES ('Argentine');
INSERT INTO `countries` (countryName) VALUES ('Belarus');
INSERT INTO `countries` (countryName) VALUES ('Erythree');
INSERT INTO `countries` (countryName) VALUES ('Papouasie Nouvelle-Guinee');
INSERT INTO `countries` (countryName) VALUES ('Lebanon');
INSERT INTO `countries` (countryName) VALUES ('Ouzbekistan');
INSERT INTO `countries` (countryName) VALUES ('Équateur');
INSERT INTO `countries` (countryName) VALUES ('Corée du sud');
INSERT INTO `countries` (countryName) VALUES ('Israel');
INSERT INTO `countries` (countryName) VALUES ('Iles vierges, USA');
INSERT INTO `countries` (countryName) VALUES ('Wallis-et-Futuna');
INSERT INTO `countries` (countryName) VALUES ('Hongrie');
INSERT INTO `countries` (countryName) VALUES ('Liechtenstein');
INSERT INTO `countries` (countryName) VALUES ('Antigue-et-Barbude');
INSERT INTO `countries` (countryName) VALUES ('Suede');
INSERT INTO `countries` (countryName) VALUES ('Palestine');
INSERT INTO `countries` (countryName) VALUES ('Etats-Unis');
INSERT INTO `countries` (countryName) VALUES ('Australie');
INSERT INTO `countries` (countryName) VALUES ('Barbade');
INSERT INTO `countries` (countryName) VALUES ('Lithuanie');
INSERT INTO `countries` (countryName) VALUES ('Mexique');
INSERT INTO `countries` (countryName) VALUES ('Micronesie');
INSERT INTO `countries` (countryName) VALUES ('Iles Pitcairn');
INSERT INTO `countries` (countryName) VALUES ('Indonesie');
INSERT INTO `countries` (countryName) VALUES ('Yémen');
INSERT INTO `countries` (countryName) VALUES ('Arabie Saoudite');
INSERT INTO `countries` (countryName) VALUES ('Senegal');
INSERT INTO `countries` (countryName) VALUES ('Armenie');
INSERT INTO `countries` (countryName) VALUES ('Saint Lucie');
INSERT INTO `countries` (countryName) VALUES ('El Salvador');
INSERT INTO `countries` (countryName) VALUES ('Porto Rico');
INSERT INTO `countries` (countryName) VALUES ('Belize');
INSERT INTO `countries` (countryName) VALUES ('Afghanistan');
INSERT INTO `countries` (countryName) VALUES ('Curaçao');
INSERT INTO `countries` (countryName) VALUES ('Iles Cook');
INSERT INTO `countries` (countryName) VALUES ('Iraq');
INSERT INTO `countries` (countryName) VALUES ('Anguilla');
INSERT INTO `countries` (countryName) VALUES ('Maroc');
INSERT INTO `countries` (countryName) VALUES ('Taiwan');
INSERT INTO `countries` (countryName) VALUES ('Aruba');
INSERT INTO `countries` (countryName) VALUES ('Croatie');
INSERT INTO `countries` (countryName) VALUES ('Angola');
INSERT INTO `countries` (countryName) VALUES ('Roumanie');
INSERT INTO `countries` (countryName) VALUES ('Egypte');
INSERT INTO `countries` (countryName) VALUES ('Turkmenistan');
INSERT INTO `countries` (countryName) VALUES ('Turquie');
INSERT INTO `countries` (countryName) VALUES ('Seychelles');
INSERT INTO `countries` (countryName) VALUES ('Espagne');
INSERT INTO `countries` (countryName) VALUES ('Macao');
INSERT INTO `countries` (countryName) VALUES ('Emirats Arabes Unis');
INSERT INTO `countries` (countryName) VALUES ('Finlande');
INSERT INTO `countries` (countryName) VALUES ('Guatemala');
INSERT INTO `countries` (countryName) VALUES ('Algerie');
INSERT INTO `countries` (countryName) VALUES ('Chili');
INSERT INTO `countries` (countryName) VALUES ('Autriche');
INSERT INTO `countries` (countryName) VALUES ('Mongolie');
INSERT INTO `countries` (countryName) VALUES ('Bangladesh');
INSERT INTO `countries` (countryName) VALUES ('Malaysie');
INSERT INTO `countries` (countryName) VALUES ('Mali');
INSERT INTO `countries` (countryName) VALUES ('Congo');
INSERT INTO `countries` (countryName) VALUES ('Chine');
INSERT INTO `countries` (countryName) VALUES ('Iles Coco');
INSERT INTO `countries` (countryName) VALUES ('Kiribati');
INSERT INTO `countries` (countryName) VALUES ('Tonga');
INSERT INTO `countries` (countryName) VALUES ('Russie');
INSERT INTO `countries` (countryName) VALUES ('Afrique du Sud');
INSERT INTO `countries` (countryName) VALUES ('Géorgie du Sud');
INSERT INTO `countries` (countryName) VALUES ('Peru');
INSERT INTO `countries` (countryName) VALUES ('Nepal');
INSERT INTO `countries` (countryName) VALUES ('Brésil');
INSERT INTO `countries` (countryName) VALUES ('Inde');
INSERT INTO `countries` (countryName) VALUES ('Honduras');
INSERT INTO `countries` (countryName) VALUES ('France');
INSERT INTO `countries` (countryName) VALUES ('Suisse');
INSERT INTO `countries` (countryName) VALUES ('Japon');
INSERT INTO `countries` (countryName) VALUES ('Hollande');
INSERT INTO `countries` (countryName) VALUES ('Singapour');
INSERT INTO `countries` (countryName) VALUES ('Martinique');
INSERT INTO `countries` (countryName) VALUES ('Vietnam');
INSERT INTO `countries` (countryName) VALUES ('Gabon');
INSERT INTO `countries` (countryName) VALUES ('Norfolk Island');
INSERT INTO `countries` (countryName) VALUES ('Portugal');
INSERT INTO `countries` (countryName) VALUES ('Saint Helena');
INSERT INTO `countries` (countryName) VALUES ('Tanzanie');
INSERT INTO `countries` (countryName) VALUES ('Rwanda');
INSERT INTO `countries` (countryName) VALUES ('Belgique');
INSERT INTO `countries` (countryName) VALUES ('Italie');
INSERT INTO `countries` (countryName) VALUES ('Angleterre');
INSERT INTO `countries` (countryName) VALUES ('Northern Mariana Islands');
INSERT INTO `countries` (countryName) VALUES ('Montserrat');
INSERT INTO `countries` (countryName) VALUES ('Ecosse');
INSERT INTO `countries` (countryName) VALUES ('Syrie');
INSERT INTO `countries` (countryName) VALUES ('Allemagne');
INSERT INTO `countries` (countryName) VALUES ('Bulgarie');
INSERT INTO `countries` (countryName) VALUES ('Saint Bonaire');
INSERT INTO `countries` (countryName) VALUES ('Zambie');
